[package]
name = "DeployerApp"
version = "0.1.0"
description = "DeployerApp una aplicación para el desplieque de sitios web, manteniendo el control de los datos en una BD localmente - by IDMarinas"
authors = ["IDMarinas"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.dev]
incremental = true # Compile your binary in smaller steps.

[profile.release]
codegen-units = 1 # Allows LLVM to perform better optimization.
lto = true        # Enables link-time-optimizations.
opt-level = "s"   # Prioritizes small binary size. Use `3` if you prefer speed.
panic = "abort"   # Higher performance by disabling panic handlers.
strip = true      # Ensures debug symbols are removed.

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "deployer_app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2.11.5", features = ["tray-icon"] }
tauri-plugin-opener = "2.5.4"
tauri-plugin-dialog = "2.7"
tauri-plugin-store = "2.4"
tauri-plugin-positioner = { version = "2.3", features = ["tray-icon"] }
tauri-plugin-sql = { version = "2.4", features = ["sqlite"] }
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.150"
sqlx = { version = "0.8.6", features = ["runtime-tokio", "sqlite", "macros", "migrate"] }
tokio = { version = "1.52.3", features = ["time"] }
ts-rs = "12.0.1"
russh = "0.61.2"
russh-sftp = "2.0.6"
chrono = { version = "0.4.45", features = ["serde"] }
aes-gcm = "0.10.3"
keyring = { version = "3.6.3", features = ["windows-native"] }
base64 = "0.22.1"
paste = "1.0"
rand = { version = "0.10.2", default-features = false, features = ["sys_rng"] }
rand_core = { version = "0.10.1" }
hex = "0.4.3"
deployer-macros = { path = "crates/deployer-macros" }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-positioner = "2"
tauri-plugin-single-instance = "2"
tauri-plugin-window-state = "2"
