// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Tipo de autenticación SSH soportado por la aplicación.
 * Solo puede ser `password` (contraseña) o `key` (clave privada).
 */
export type AuthType = "password" | "key";

export type CommandResponse<T = null> = { success: boolean, data: T | null, message_key: string, message_params: { [key in string]: string }, };

export type CreateDeploymentExecutionInput = { deployment_id: number, host_id: number, task_id: number, retry_attempt: number | null, };

export type CreateDeploymentInput = { project_id: number, version: string, tag: string, build: number, triggered_by: string | null, notes: string | null, };

export type CreateDeploymentRollbackInput = { deployment_id: number, rolled_back_to_deployment_id: number, reason: string | null, triggered_by: string | null, };

export type CreateFrameworkConfigInput = { project_id: number, framework: Framework, key: string, value: string, is_secret: boolean | null, data_type: DataType | null, description: string | null, };

export type CreateGlobalVariableInput = { name: string, value: string, is_secret: boolean | null, description: string | null, };

export type CreateHostInput = { name: string, host: string, port: number | null, username: string, auth_type: AuthType, password: string | null, key_id: number | null, description: string | null, enabled: boolean | null, };

export type CreatePasskeyInput = { name: string, key_content: string, passphrase: string | null, key_type: KeyType | null, fingerprint: string | null, description: string | null, };

export type CreateProjectHostInput = { project_id: number, host_id: number, deploy_order: number | null, enabled: boolean | null, };

export type CreateProjectInput = { name: string, description: string | null, git_url: string | null, framework: string, enabled: boolean | null, };

export type CreateProjectTaskInput = { project_id: number, task_id: number, order_execution: number, enabled: boolean | null, condition: string | null, on_failure: OnFailure | null, };

export type CreateProjectVariableInput = { project_id: number, name: string, value: string, is_secret: boolean | null, description: string | null, };

export type CreateTaskDependencyInput = { task_id: number, depends_on_task_id: number, dependency_type: DependencyType | null, };

export type CreateTaskInput = { name: string, description: string | null, task_type: TaskType, command: string | null, working_dir: string | null, timeout: number | null, retry_count: number | null, enabled: boolean | null, is_global: boolean | null, };

export type DataType = "string" | "integer" | "boolean" | "json";

export type DependencyType = "success" | "failure" | "always";

/**
 * Par clave-valor de la tabla `deployer_settings`.
 */
export type DeployerSetting = { key: string, value: string | null, };

export type Deployment = { id: number, project_id: number, version: string, tag: string, build: number, status: DeploymentStatus, started_at: string | null, finished_at: string | null, duration_seconds: number | null, triggered_by: string | null, notes: string | null, created_at: string, };

export type DeploymentExecution = { id: number, deployment_id: number, host_id: number, task_id: number, status: ExecutionStatus, exit_code: number | null, output: string | null, error_message: string | null, started_at: string | null, finished_at: string | null, duration_seconds: number | null, retry_attempt: number, created_at: string, };

export type DeploymentRollback = { id: number, deployment_id: number, rolled_back_to_deployment_id: number, status: DeploymentStatus, reason: string | null, triggered_by: string | null, started_at: string | null, finished_at: string | null, created_at: string, };

export type DeploymentStatus = "pending" | "running" | "success" | "failed";

export type ExecutionStatus = "pending" | "running" | "success" | "failed" | "skipped";

export type ExportPublicKeyAction = "add" | "remove";

export type ExportPublicKeyInput = { 
/**
 * ID del host destino donde se exportará la clave pública.
 */
host_id: number, 
/**
 * ID de la passkey cuya clave pública se exportará.
 */
passkey_id: number, 
/**
 * Acción a realizar: añadir o eliminar la clave del authorized_keys.
 */
action: ExportPublicKeyAction, 
/**
 * Credenciales temporales opcionales. Se usan cuando el host no tiene
 * credenciales guardadas en BD que funcionen (ej: host con auth por key
 * pero la passkey aún no está en el servidor).
 */
temp_username: string | null, temp_password: string | null, };

export type Framework = "symfony" | "laravel" | "nextjs" | "generic";

export type FrameworkConfig = { id: number, project_id: number, framework: Framework, key: string, value: string, is_secret: boolean, data_type: DataType, description: string | null, created_at: string, updated_at: string, };

export type GeneratePasskeyInput = { 
/**
 * Tipo de clave a generar. Por defecto: Ed25519.
 */
key_type: KeyType | null, 
/**
 * Passphrase para proteger la clave privada.
 * `None` o cadena vacía = sin passphrase.
 */
passphrase: string | null, };

export type GeneratedPasskey = { 
/**
 * Clave privada en formato OpenSSH (texto plano).
 * El cifrado lo aplica `crud_create_passkey` al guardar en BD.
 */
key_content: string, 
/**
 * Clave pública en formato OpenSSH (para añadir al servidor remoto).
 */
public_key: string, 
/**
 * Fingerprint SHA-256 de la clave (formato `SHA256:...`).
 */
fingerprint: string, 
/**
 * Tipo de clave generada.
 */
key_type: KeyType, 
/**
 * Passphrase ya cifrada con AES-256-GCM, lista para pasar directamente
 * a `crud_create_passkey`. `None` si no se solicitó passphrase.
 */
passphrase: string | null, };

export type GlobalVariable = { id: number, name: string, value: string, is_secret: boolean, description: string | null, created_at: string, updated_at: string, };

export type Host = { id: number, name: string, host: string, port: number, username: string, auth_type: AuthType, 
/**
 * Cifrado siempre. `expose = false`: el frontend no necesita leerla en texto plano;
 * solo la usa Rust internamente para SSH.
 */
password: string | null, key_id: number | null, description: string | null, enabled: boolean, created_at: string, updated_at: string, };

export type KeyType = "rsa" | "ed25519" | "ecdsa";

export type OnFailure = "stop" | "continue" | "retry";

export type Passkey = { id: number, name: string, key_content: string, passphrase: string | null, key_type: KeyType | null, fingerprint: string | null, description: string | null, created_at: string, updated_at: string, };

export type Project = { id: number, name: string, description: string | null, git_url: string | null, framework: string, enabled: boolean, created_at: string, updated_at: string, };

export type ProjectHost = { id: number, project_id: number, host_id: number, deploy_order: number | null, enabled: boolean, created_at: string, };

export type ProjectTask = { id: number, project_id: number, task_id: number, order_execution: number, enabled: boolean, condition: string | null, on_failure: OnFailure, created_at: string, updated_at: string, };

export type ProjectVariable = { id: number, project_id: number, name: string, value: string, is_secret: boolean, description: string | null, created_at: string, updated_at: string, };

export type Task = { id: number, name: string, description: string | null, type: TaskType, command: string | null, working_dir: string | null, timeout: number, retry_count: number, enabled: boolean, is_global: boolean, created_at: string, updated_at: string, };

export type TaskDependency = { id: number, task_id: number, depends_on_task_id: number, dependency_type: DependencyType, created_at: string, };

export type TaskType = "command" | "upload_file" | "download_file" | "script";

export type UpdateDeploymentExecutionInput = { status: ExecutionStatus | null, exit_code: number | null, output: string | null, error_message: string | null, started_at: string | null, finished_at: string | null, duration_seconds: number | null, retry_attempt: number | null, };

export type UpdateDeploymentInput = { status: DeploymentStatus | null, started_at: string | null, finished_at: string | null, duration_seconds: number | null, notes: string | null, };

export type UpdateDeploymentRollbackInput = { status: DeploymentStatus | null, started_at: string | null, finished_at: string | null, };

export type UpdateFrameworkConfigInput = { value: string | null, is_secret: boolean | null, data_type: DataType | null, description: string | null, };

export type UpdateGlobalVariableInput = { name: string | null, value: string | null, is_secret: boolean | null, description: string | null, };

export type UpdateHostInput = { name: string | null, host: string | null, port: number | null, username: string | null, auth_type: AuthType | null, 
/**
 * Si es `None`, no se modifica la contraseña actual.
 * Si es `Some("")`, se elimina la contraseña.
 * Si es `Some("valor")`, se cifra y se guarda.
 */
password: string | null, key_id: number | null, description: string | null, enabled: boolean | null, };

export type UpdatePasskeyInput = { name: string | null, 
/**
 * Si es `None`, no se modifica el contenido actual.
 * Si es `Some("valor")`, se cifra y se guarda.
 */
key_content: string | null, 
/**
 * Si es `None`, no se modifica la passphrase actual.
 * Si es `Some("")`, se elimina la passphrase.
 */
passphrase: string | null, key_type: KeyType | null, fingerprint: string | null, description: string | null, };

export type UpdateProjectHostInput = { deploy_order: number | null, enabled: boolean | null, };

export type UpdateProjectInput = { name: string | null, description: string | null, git_url: string | null, framework: string | null, enabled: boolean | null, };

export type UpdateProjectTaskInput = { order_execution: number | null, enabled: boolean | null, condition: string | null, on_failure: OnFailure | null, };

export type UpdateProjectVariableInput = { name: string | null, value: string | null, is_secret: boolean | null, description: string | null, };

export type UpdateTaskDependencyInput = { dependency_type: DependencyType, };

export type UpdateTaskInput = { name: string | null, description: string | null, task_type: TaskType | null, command: string | null, working_dir: string | null, timeout: number | null, retry_count: number | null, enabled: boolean | null, is_global: boolean | null, };
