// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CommandResponse<T = null> = { success: boolean, data: T | null, message_key: string, message_params: { [key in string]: string }, };

export type CreateHostInput = { name: string, host: string, port: number | null, username: string | null, auth_type: string, password: string | null, key_id: number | null, description: string | null, enabled: boolean | null, };

export type Host = { id: number, name: string, host: string, port: number, username: string | null, auth_type: string, password: string | null, key_id: number | null, description: string | null, enabled: boolean, created_at: string, updated_at: string, };

export type UpdateHostInput = { name: string | null, host: string | null, port: number | null, username: string | null, auth_type: string | null, 
/**
 * Si es `None`, no se modifica la contraseña actual.
 * Si es `Some("")`, se elimina la contraseña.
 * Si es `Some("valor")`, se cifra y se guarda.
 */
password: string | null, key_id: number | null, description: string | null, enabled: boolean | null, };
