/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'
import type {
  _ExtractParamParserType,
} from 'vue-router/experimental'

declare module 'vue-router' {
  interface TypesConfig {
    _ParamParsers: {}
    RouteNamedMap: import('vue-router/auto-routes').RouteNamedMap
    _RouteFileInfoMap: import('vue-router/auto-routes')._RouteFileInfoMap
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/dashboard': RouteRecordInfo<
      '/dashboard',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/[...path]'
      | '/dashboard/app'
      | '/dashboard/deployments'
      | '/dashboard/deployments/[...path]'
      | '/dashboard/deployments/add'
      | '/dashboard/docker_composes'
      | '/dashboard/docker_composes/[...path]'
      | '/dashboard/hosts'
      | '/dashboard/passkeys'
      | '/dashboard/passkeys/[...path]'
      | '/dashboard/projects'
      | '/dashboard/projects/[...path]'
      | '/dashboard/tasks'
      | '/dashboard/tasks/[...path]'
      | '/dashboard/variables'
      | '/dashboard/variables/[...path]'
      | 'dashboard-app'
      | 'dashboard-deployments'
      | 'dashboard-deployments-id-edit'
      | 'dashboard-docker_composes'
      | 'dashboard-docker_composes-add'
      | 'dashboard-docker_composes-id'
      | 'dashboard-docker_composes-id-edit'
      | 'dashboard-global_variables'
      | 'dashboard-global_variables-add'
      | 'dashboard-global_variables-id-edit'
      | 'dashboard-home'
      | 'dashboard-hosts'
      | 'dashboard-hosts-add'
      | 'dashboard-hosts-id-edit'
      | 'dashboard-hosts-not-found'
      | 'dashboard-passkeys'
      | 'dashboard-passkeys-add'
      | 'dashboard-passkeys-id-edit'
      | 'dashboard-projects'
      | 'dashboard-projects-add'
      | 'dashboard-projects-id'
      | 'dashboard-projects-id-edit'
      | 'dashboard-tasks'
      | 'dashboard-tasks-add'
      | 'dashboard-tasks-id-edit'
    >,
    'dashboard-home': RouteRecordInfo<
      'dashboard-home',
      '/dashboard',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/[...path]': RouteRecordInfo<
      '/dashboard/[...path]',
      '/dashboard/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/dashboard/app': RouteRecordInfo<
      '/dashboard/app',
      '/dashboard/app',
      Record<never, never>,
      Record<never, never>,
      | 'dashboard-app'
    >,
    'dashboard-app': RouteRecordInfo<
      'dashboard-app',
      '/dashboard/app',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/deployments': RouteRecordInfo<
      '/dashboard/deployments',
      '/dashboard/deployments',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/deployments/[...path]'
      | '/dashboard/deployments/add'
      | 'dashboard-deployments'
      | 'dashboard-deployments-id-edit'
    >,
    'dashboard-deployments': RouteRecordInfo<
      'dashboard-deployments',
      '/dashboard/deployments',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/deployments/[...path]': RouteRecordInfo<
      '/dashboard/deployments/[...path]',
      '/dashboard/deployments/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'dashboard-deployments-id-edit': RouteRecordInfo<
      'dashboard-deployments-id-edit',
      '/dashboard/deployments/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dashboard/deployments/add': RouteRecordInfo<
      '/dashboard/deployments/add',
      '/dashboard/deployments/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/docker_composes': RouteRecordInfo<
      '/dashboard/docker_composes',
      '/dashboard/docker_composes',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/docker_composes/[...path]'
      | 'dashboard-docker_composes'
      | 'dashboard-docker_composes-add'
      | 'dashboard-docker_composes-id'
      | 'dashboard-docker_composes-id-edit'
    >,
    'dashboard-docker_composes': RouteRecordInfo<
      'dashboard-docker_composes',
      '/dashboard/docker_composes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/docker_composes/[...path]': RouteRecordInfo<
      '/dashboard/docker_composes/[...path]',
      '/dashboard/docker_composes/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'dashboard-docker_composes-id': RouteRecordInfo<
      'dashboard-docker_composes-id',
      '/dashboard/docker_composes/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'dashboard-docker_composes-id-edit': RouteRecordInfo<
      'dashboard-docker_composes-id-edit',
      '/dashboard/docker_composes/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'dashboard-docker_composes-add': RouteRecordInfo<
      'dashboard-docker_composes-add',
      '/dashboard/docker_composes/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/hosts': RouteRecordInfo<
      '/dashboard/hosts',
      '/dashboard/hosts',
      Record<never, never>,
      Record<never, never>,
      | 'dashboard-hosts'
      | 'dashboard-hosts-add'
      | 'dashboard-hosts-id-edit'
      | 'dashboard-hosts-not-found'
    >,
    'dashboard-hosts': RouteRecordInfo<
      'dashboard-hosts',
      '/dashboard/hosts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-hosts-not-found': RouteRecordInfo<
      'dashboard-hosts-not-found',
      '/dashboard/hosts/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'dashboard-hosts-id-edit': RouteRecordInfo<
      'dashboard-hosts-id-edit',
      '/dashboard/hosts/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'dashboard-hosts-add': RouteRecordInfo<
      'dashboard-hosts-add',
      '/dashboard/hosts/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/passkeys': RouteRecordInfo<
      '/dashboard/passkeys',
      '/dashboard/passkeys',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/passkeys/[...path]'
      | 'dashboard-passkeys'
      | 'dashboard-passkeys-add'
      | 'dashboard-passkeys-id-edit'
    >,
    'dashboard-passkeys': RouteRecordInfo<
      'dashboard-passkeys',
      '/dashboard/passkeys',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/passkeys/[...path]': RouteRecordInfo<
      '/dashboard/passkeys/[...path]',
      '/dashboard/passkeys/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'dashboard-passkeys-id-edit': RouteRecordInfo<
      'dashboard-passkeys-id-edit',
      '/dashboard/passkeys/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'dashboard-passkeys-add': RouteRecordInfo<
      'dashboard-passkeys-add',
      '/dashboard/passkeys/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/projects': RouteRecordInfo<
      '/dashboard/projects',
      '/dashboard/projects',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/projects/[...path]'
      | 'dashboard-projects'
      | 'dashboard-projects-add'
      | 'dashboard-projects-id'
      | 'dashboard-projects-id-edit'
    >,
    'dashboard-projects': RouteRecordInfo<
      'dashboard-projects',
      '/dashboard/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    'dashboard-projects-id': RouteRecordInfo<
      'dashboard-projects-id',
      '/dashboard/projects/:id(\\d+)',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'dashboard-projects-id-edit': RouteRecordInfo<
      'dashboard-projects-id-edit',
      '/dashboard/projects/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    '/dashboard/projects/[...path]': RouteRecordInfo<
      '/dashboard/projects/[...path]',
      '/dashboard/projects/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'dashboard-projects-add': RouteRecordInfo<
      'dashboard-projects-add',
      '/dashboard/projects/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/tasks': RouteRecordInfo<
      '/dashboard/tasks',
      '/dashboard/tasks',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/tasks/[...path]'
      | 'dashboard-tasks'
      | 'dashboard-tasks-add'
      | 'dashboard-tasks-id-edit'
    >,
    'dashboard-tasks': RouteRecordInfo<
      'dashboard-tasks',
      '/dashboard/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/tasks/[...path]': RouteRecordInfo<
      '/dashboard/tasks/[...path]',
      '/dashboard/tasks/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'dashboard-tasks-id-edit': RouteRecordInfo<
      'dashboard-tasks-id-edit',
      '/dashboard/tasks/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'dashboard-tasks-add': RouteRecordInfo<
      'dashboard-tasks-add',
      '/dashboard/tasks/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/variables': RouteRecordInfo<
      '/dashboard/variables',
      '/dashboard/variables',
      Record<never, never>,
      Record<never, never>,
      | '/dashboard/variables/[...path]'
      | 'dashboard-global_variables'
      | 'dashboard-global_variables-add'
      | 'dashboard-global_variables-id-edit'
    >,
    'dashboard-global_variables': RouteRecordInfo<
      'dashboard-global_variables',
      '/dashboard/variables',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dashboard/variables/[...path]': RouteRecordInfo<
      '/dashboard/variables/[...path]',
      '/dashboard/variables/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    'dashboard-global_variables-id-edit': RouteRecordInfo<
      'dashboard-global_variables-id-edit',
      '/dashboard/global_variables/:id(\\d+)/edit',
      { id: ParamValue<true> },
      { id: ParamValue<false> },
      | never
    >,
    'dashboard-global_variables-add': RouteRecordInfo<
      'dashboard-global_variables-add',
      '/dashboard/variables/add',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/deployer': RouteRecordInfo<
      '/deployer',
      '/deployer',
      Record<never, never>,
      Record<never, never>,
      | '/deployer/(setup)'
      | '/deployer/[...path]'
      | '/deployer/migrations'
    >,
    '/deployer/(setup)': RouteRecordInfo<
      '/deployer/(setup)',
      '/deployer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/deployer/[...path]': RouteRecordInfo<
      '/deployer/[...path]',
      '/deployer/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/deployer/migrations': RouteRecordInfo<
      '/deployer/migrations',
      '/deployer/migrations',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/dashboard.vue': {
      routes:
        | '/dashboard'
        | '/dashboard/[...path]'
        | '/dashboard/app'
        | '/dashboard/deployments'
        | '/dashboard/deployments/[...path]'
        | '/dashboard/deployments/add'
        | '/dashboard/docker_composes'
        | '/dashboard/docker_composes/[...path]'
        | '/dashboard/hosts'
        | '/dashboard/passkeys'
        | '/dashboard/passkeys/[...path]'
        | '/dashboard/projects'
        | '/dashboard/projects/[...path]'
        | '/dashboard/tasks'
        | '/dashboard/tasks/[...path]'
        | '/dashboard/variables'
        | '/dashboard/variables/[...path]'
        | 'dashboard-app'
        | 'dashboard-deployments'
        | 'dashboard-deployments-id-edit'
        | 'dashboard-docker_composes'
        | 'dashboard-docker_composes-add'
        | 'dashboard-docker_composes-id'
        | 'dashboard-docker_composes-id-edit'
        | 'dashboard-global_variables'
        | 'dashboard-global_variables-add'
        | 'dashboard-global_variables-id-edit'
        | 'dashboard-home'
        | 'dashboard-hosts'
        | 'dashboard-hosts-add'
        | 'dashboard-hosts-id-edit'
        | 'dashboard-hosts-not-found'
        | 'dashboard-passkeys'
        | 'dashboard-passkeys-add'
        | 'dashboard-passkeys-id-edit'
        | 'dashboard-projects'
        | 'dashboard-projects-add'
        | 'dashboard-projects-id'
        | 'dashboard-projects-id-edit'
        | 'dashboard-tasks'
        | 'dashboard-tasks-add'
        | 'dashboard-tasks-id-edit'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/dashboard/(dashboard).vue': {
      routes:
        | 'dashboard-home'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/[...path].vue': {
      routes:
        | '/dashboard/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/dashboard/app.vue': {
      routes:
        | '/dashboard/app'
        | 'dashboard-app'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/dashboard/app/index.vue': {
      routes:
        | 'dashboard-app'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/deployments.vue': {
      routes:
        | '/dashboard/deployments'
        | '/dashboard/deployments/[...path]'
        | '/dashboard/deployments/add'
        | 'dashboard-deployments'
        | 'dashboard-deployments-id-edit'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/dashboard/deployments/index.vue': {
      routes:
        | 'dashboard-deployments'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/deployments/[...path].vue': {
      routes:
        | '/dashboard/deployments/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/dashboard/deployments/[id].edit.vue': {
      routes:
        | 'dashboard-deployments-id-edit'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dashboard/deployments/add.vue': {
      routes:
        | '/dashboard/deployments/add'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/docker_composes.vue': {
      routes:
        | '/dashboard/docker_composes'
        | '/dashboard/docker_composes/[...path]'
        | 'dashboard-docker_composes'
        | 'dashboard-docker_composes-add'
        | 'dashboard-docker_composes-id'
        | 'dashboard-docker_composes-id-edit'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/dashboard/docker_composes/index.vue': {
      routes:
        | 'dashboard-docker_composes'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/docker_composes/[...path].vue': {
      routes:
        | '/dashboard/docker_composes/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/dashboard/docker_composes/[id].vue': {
      routes:
        | 'dashboard-docker_composes-id'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dashboard/docker_composes/[id].edit.vue': {
      routes:
        | 'dashboard-docker_composes-id-edit'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dashboard/docker_composes/add.vue': {
      routes:
        | 'dashboard-docker_composes-add'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/hosts.vue': {
      routes:
        | '/dashboard/hosts'
        | 'dashboard-hosts'
        | 'dashboard-hosts-add'
        | 'dashboard-hosts-id-edit'
        | 'dashboard-hosts-not-found'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/dashboard/hosts/index.vue': {
      routes:
        | 'dashboard-hosts'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/hosts/[...path].vue': {
      routes:
        | 'dashboard-hosts-not-found'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/dashboard/hosts/[id].edit.vue': {
      routes:
        | 'dashboard-hosts-id-edit'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dashboard/hosts/add.vue': {
      routes:
        | 'dashboard-hosts-add'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/passkeys.vue': {
      routes:
        | '/dashboard/passkeys'
        | '/dashboard/passkeys/[...path]'
        | 'dashboard-passkeys'
        | 'dashboard-passkeys-add'
        | 'dashboard-passkeys-id-edit'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/dashboard/passkeys/index.vue': {
      routes:
        | 'dashboard-passkeys'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/passkeys/[...path].vue': {
      routes:
        | '/dashboard/passkeys/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/dashboard/passkeys/[id].edit.vue': {
      routes:
        | 'dashboard-passkeys-id-edit'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dashboard/passkeys/add.vue': {
      routes:
        | 'dashboard-passkeys-add'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/projects.vue': {
      routes:
        | '/dashboard/projects'
        | '/dashboard/projects/[...path]'
        | 'dashboard-projects'
        | 'dashboard-projects-add'
        | 'dashboard-projects-id'
        | 'dashboard-projects-id-edit'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/dashboard/projects/index.vue': {
      routes:
        | 'dashboard-projects'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/projects/[id]/(view).vue': {
      routes:
        | 'dashboard-projects-id'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/projects/[id]/edit.vue': {
      routes:
        | 'dashboard-projects-id-edit'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/projects/[...path].vue': {
      routes:
        | '/dashboard/projects/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/dashboard/projects/add.vue': {
      routes:
        | 'dashboard-projects-add'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/tasks.vue': {
      routes:
        | '/dashboard/tasks'
        | '/dashboard/tasks/[...path]'
        | 'dashboard-tasks'
        | 'dashboard-tasks-add'
        | 'dashboard-tasks-id-edit'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/dashboard/tasks/index.vue': {
      routes:
        | 'dashboard-tasks'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/tasks/[...path].vue': {
      routes:
        | '/dashboard/tasks/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/dashboard/tasks/[id].edit.vue': {
      routes:
        | 'dashboard-tasks-id-edit'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dashboard/tasks/add.vue': {
      routes:
        | 'dashboard-tasks-add'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/variables.vue': {
      routes:
        | '/dashboard/variables'
        | '/dashboard/variables/[...path]'
        | 'dashboard-global_variables'
        | 'dashboard-global_variables-add'
        | 'dashboard-global_variables-id-edit'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/dashboard/variables/index.vue': {
      routes:
        | 'dashboard-global_variables'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/dashboard/variables/[...path].vue': {
      routes:
        | '/dashboard/variables/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/dashboard/variables/[id].edit.vue': {
      routes:
        | 'dashboard-global_variables-id-edit'
      views:
        | never
      pathParamNames:
        | 'id'
    }
    'src/pages/dashboard/variables/add.vue': {
      routes:
        | 'dashboard-global_variables-add'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/deployer.vue': {
      routes:
        | '/deployer'
        | '/deployer/(setup)'
        | '/deployer/[...path]'
        | '/deployer/migrations'
      views:
        | 'default'
      pathParamNames:
        | never
    }
    'src/pages/deployer/(setup).vue': {
      routes:
        | '/deployer/(setup)'
      views:
        | never
      pathParamNames:
        | never
    }
    'src/pages/deployer/[...path].vue': {
      routes:
        | '/deployer/[...path]'
      views:
        | never
      pathParamNames:
        | 'path'
    }
    'src/pages/deployer/migrations.vue': {
      routes:
        | '/deployer/migrations'
      views:
        | never
      pathParamNames:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
